config/routes.rb
Rails.application.routes.draw do
  devise_for :males, controllers:{
    sessions:        'males/sessions',
    passwords:       'males/passwords',
    registrations:   'males/registrations'
  }
  devise_for :lady_doctors, controllers:{
    sessions:        'lady_doctors/sessions',
    passwords:       'lady_doctors/passwords',
    registrations:   'lady_doctors/registrations'
  }
  devise_for :admins, controllers:{
    sessions:        'admins/sessions',
    passwords:       'admins/passwords',
    registrations:   'admins/registrations'
  }
  

  devise_scope :male do
      get "/", :to => "males/sessions#new"
  end

 
  

  resources :admins, only: [:index]
  get "admins/confirm/:id" => "admins#confirm"

  get "males/:male_id/lady_doctor_posts/:id/comment" => "male_post_comments#new", as: :new_male_post_comment
  post "males/:male_id/profile_image/:id" => 'males#profile_update', as: :male_image
  get 'males/:male_id/lady_doctor_posts/:id' => 'males#lady_doctor_posts_show', as: :lady_doctor_posts_show
  get 'males/:male_id/lady_doctor/:id' => 'males#lady_doctor_index', as: :lady_doctor_index

  resources :males do
    member do
      get :following
      get :unfollowing, only: [:index]      
    end
    resources :male_posts
  end
  
  get 'males/:male_id/following/lady_docotrs/:id' => 'males#following_index', as: :following_index
  get 'males/:male_id/unfollowing/lady_docotrs/:id' => 'males#unfollowing_index', as: :unfollowing_index

  resources :male_post_comments, except: [:new]
  

 
  

  resources :lady_doctors do
    resources :lady_doctor_posts
  end
  
  get "lady_doctors/:lady_doctor_id/lady_doctor_posts/:lady_doctor_post_id/follow_male/:id" => 'lady_doctor_posts#male_show', as: :commenter  

 
  get 'lady_doctors/:lady_doctor_id/follow_male/:id' => 'lady_doctors#follow_show', as: :follower
  post "lady_doctors/:lady_doctor_id/profile_image/:id" => 'lady_doctors#profile_update', as: :lady_doctor_image
  

  resources :relationships, path: "lady_doctors/:id/follow", only: [:create]
  resources :relationships, path: "lady_doctors/:lady_doctor_id/unfollow", only: [:destroy]

  resources :likes, path: "males/:id/like", only: [:create]
  resources :likes, path: "males/:male_id/unlike", only: [:destroy]

  resources :male_blocks, path: "males/:male_id/lady_doctors/:id/block", only: [:create]
  resources :male_blocks, path: "males/:male_id/lady_doctors/:lady_doctor_id/unblock", only: [:destroy]
  
  resources :lady_doctor_blocks, path: "lady_doctors/:lady_doctor_id/males/:id/block", only: [:create]
  resources :lady_doctor_blocks, path: "lady_doctors/:lady_doctor_id/males/:male_id/unblock", only: [:destroy]

  
  

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/annual_income.rb
class AnnualIncome < ActiveRecord::Base
end

app/models/interest.rb
class Interest < ActiveRecord::Base
end

app/models/lady_doctor.rb
class LadyDoctor < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  #done 'follow'
  has_many :follower_relationships, foreign_key: "lady_doctor_id", class_name: "Relationship", dependent: :destroy
  has_many :followers, through: :follower_relationships
  has_many :lady_doctor_posts

  #do 'like'
  #has_many :sending_likes, foreign_key: "male_id", class_name: "Like", dependent: :destroy
  has_many :likes

  has_many :lady_doctor_blocks

  validates :name, presence: true
  validates :doctor_number, presence: true

  def blocking?(male)
    lady_doctor_blocks.find_by(male_id: male.id) != nil
  end
  

  def sending?(male)
  	#p "--------------------------------"
  	#p self.id, male.id
  	#p likes.find_by(male_id: male.id) != nil
  	#p "--------------------------------"
    likes.find_by(male_id: male.id) != nil
  end

end

app/models/lady_doctor_block.rb
class LadyDoctorBlock < ActiveRecord::Base
  belongs_to :lady_doctor
end

app/models/lady_doctor_post.rb
class LadyDoctorPost < ActiveRecord::Base
	belongs_to :lady_doctor
	has_many :male_post_comments

  validates :lady_doctor_id, presence: true
  validates :content, presence: true

	mount_uploader :image, ImageUploader
end

app/models/like.rb
class Like < ActiveRecord::Base
end

app/models/male.rb
class Male < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  #do 'follow'
  #has_many :following_relationships, foreign_key: "male_id", class_name: "Relationship", dependent: :destroy
  has_many :following_relationships, foreign_key: "lady_doctor_id", class_name: "Relationship", dependent: :destroy
  has_many :followings, through: :following_relationships

  validates :name, presence: true  
  
  has_many :male_posts
  has_many :male_post_comments

  has_many :male_blocks

  def following?(lady_doctor)
    following_relationships.find_by(lady_doctor_id: lady_doctor.id)
  end

  def follow!(lady_doctor)
    following_relationships.create!(lady_doctor_id: lady_doctor.id)
  end

  def unfollow!(lady_doctor)
    following_relationships.find_by(lady_doctor_id: lady_doctor.id).destroy
  end

  def blocking?(lady_doctor)
    male_blocks.find_by(lady_doctor_id: lady_doctor.id) != nil
  end
  

end

app/models/male_block.rb
class MaleBlock < ActiveRecord::Base
  belongs_to :male
end

app/models/male_interests.rb
class MaleInterests < ActiveRecord::Base
end

app/models/male_post.rb
class MalePost < ActiveRecord::Base
  belongs_to :male

  mount_uploader :image, ImageUploader

  validates :male_id, presence: true
  validates :content, presence: true
end

app/models/male_post_comment.rb
class MalePostComment < ActiveRecord::Base
  belongs_to :male
  belongs_to :lady_doctor_post
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/interests_helper.rb
module InterestsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/male_blocks_helper.rb
module MaleBlocksHelper
end

app/helpers/male_posts_helper.rb
module MalePostsHelper
end

app/helpers/males_helper.rb
module MalesHelper
  def sign_in(male)
    remember_token = Male.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    male.update_attribute(:remember_token, Male.encrypt(remember_token))
    self.current_male = male
  end

  def signed_in?
    !current_male.nil?
  end

  def current_male
    remember_token = Male.encrypt(cookies[:remember_token])
    @current_male ||= Male.find_by(remember_token: remember_token)
  end

  def current_male?(male)
    male == current_male
  end

  def current_male=(male)
    @current_male = male
  end

  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end

  def signed_in_user
      redirect_to signin_url, notice: "Please sign in." unless signed_in?
  end

end

app/views/admins/index.html.erb
<div class="container">

<h1>未承認女医</h1>

<% if @lady_doctors.any? %>
 <div class="item" >
  <div class="main">
   <% @lady_doctors.each do |lady_doctor| %>
   <div class = "index">
    <span class="default">名前：</span><span class="unique"><%= lady_doctor.name %> </span> 
    <span class="default">医師登録番号:</span>
    <span class="unique"><%= lady_doctor.doctor_number %></span> 
    <%= link_to '承認', :controller => 'admins', :action => 'confirm', :id =>lady_doctor.id %>
      <br>
    </div>
  <% end %>
  </div>
<!-- main -->
</div> 
<!-- item -->
<% else %> 
  未承認女医はいません
<% end %> 


<br>

<%= link_to 'ログアウト', destroy_admin_session_path, method: :delete %>   

</div>
<!-- container -->

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LadyDoctorSns</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="body">
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>	

<%= yield %>

</body>
</html>