config/routes.rb
Rails.application.routes.draw do
  devise_for :males, controllers:{
    sessions:        'males/sessions',
    passwords:       'males/passwords',
    registrations:   'males/registrations'
  }
  devise_for :lady_doctors, controllers:{
    sessions:        'lady_doctors/sessions',
    passwords:       'lady_doctors/passwords',
    registrations:   'lady_doctors/registrations'
  }
  devise_for :admins, controllers:{
    sessions:        'admins/sessions',
    passwords:       'admins/passwords',
    registrations:   'admins/registrations'
  }
  

  devise_scope :male do
      get "/", :to => "males/sessions#new"
  end

 
  

  resources :admins, only: [:index]
  get "admins/confirm/:id" => "admins#confirm"

  get "males/:male_id/lady_doctor_posts/:id/comment" => "male_post_comments#new", as: :new_male_post_comment
  post "males/:male_id/profile_image/:id" => 'males#profile_update', as: :male_image
  get 'males/:male_id/lady_doctor_posts/:id' => 'males#lady_doctor_posts_show', as: :lady_doctor_posts_show
  get 'males/:male_id/lady_doctor/:id' => 'males#lady_doctor_index', as: :lady_doctor_index

  resources :males do
    member do
      get :following
      get :unfollowing, only: [:index]      
    end
    resources :male_posts
  end
  
  get 'males/:male_id/following/lady_docotrs/:id' => 'males#following_index', as: :following_index
  get 'males/:male_id/unfollowing/lady_docotrs/:id' => 'males#unfollowing_index', as: :unfollowing_index

  resources :male_post_comments, except: [:new]
  

 
  

  resources :lady_doctors do
    resources :lady_doctor_posts
  end
  
  get "lady_doctors/:lady_doctor_id/lady_doctor_posts/:lady_doctor_post_id/follow_male/:id" => 'lady_doctor_posts#male_show', as: :commenter  

 
  get 'lady_doctors/:lady_doctor_id/follow_male/:id' => 'lady_doctors#follow_show', as: :follower
  post "lady_doctors/:lady_doctor_id/profile_image/:id" => 'lady_doctors#profile_update', as: :lady_doctor_image
  

  resources :relationships, path: "lady_doctors/:id/follow", only: [:create]
  resources :relationships, path: "lady_doctors/:lady_doctor_id/unfollow", only: [:destroy]

  resources :likes, path: "males/:id/like", only: [:create]
  resources :likes, path: "males/:male_id/unlike", only: [:destroy]

  resources :male_blocks, path: "males/:male_id/lady_doctors/:id/block", only: [:create]
  resources :male_blocks, path: "males/:male_id/lady_doctors/:lady_doctor_id/unblock", only: [:destroy]
  
  resources :lady_doctor_blocks, path: "lady_doctors/:lady_doctor_id/males/:id/block", only: [:create]
  resources :lady_doctor_blocks, path: "lady_doctors/:lady_doctor_id/males/:male_id/unblock", only: [:destroy]

  
  

end

app/models/lady_doctor.rb
class LadyDoctor < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  #done 'follow'
  has_many :follower_relationships, foreign_key: "lady_doctor_id", class_name: "Relationship", dependent: :destroy
  has_many :followers, through: :follower_relationships
  has_many :lady_doctor_posts

  #do 'like'
  #has_many :sending_likes, foreign_key: "male_id", class_name: "Like", dependent: :destroy
  has_many :likes

  has_many :lady_doctor_blocks

  validates :name, presence: true
  validates :doctor_number, presence: true

  def blocking?(male)
    lady_doctor_blocks.find_by(male_id: male.id) != nil
  end
  

  def sending?(male)
  	#p "--------------------------------"
  	#p self.id, male.id
  	#p likes.find_by(male_id: male.id) != nil
  	#p "--------------------------------"
    likes.find_by(male_id: male.id) != nil
  end

end

app/controllers/lady_doctors/confirmations_controller.rb
class LadyDoctors::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/lady_doctors/omniauth_callbacks_controller.rb
class LadyDoctors::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when omniauth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/lady_doctors/passwords_controller.rb
class LadyDoctors::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/lady_doctors/registrations_controller.rb
class LadyDoctors::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]
before_filter :configure_permitted_parameters
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:sign_up) << :doctor_number
  end
  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # You can put the params you want to permit in the empty array.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/lady_doctors/sessions_controller.rb
class LadyDoctors::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
  def after_sign_out_path_for(resource)
    case resource
    when :male
      new_male_session_path
    when :lady_doctor
      new_lady_doctor_session_path
    #when Admin
    end
  end 
end

app/controllers/lady_doctors/unlocks_controller.rb
class LadyDoctors::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/lady_doctors_controller.rb
class LadyDoctorsController < ApplicationController
  before_action :blocked?, only: [:follow_show] 
  before_action :authenticate_lady_doctor!
  before_action :set_lady_doctor, only: [:index, :show, :edit, :update, :destroy, :profile_update]
  
  def index
    if @lady_doctor.confirm_state
      #followされているmale全て
      @title = "Follower"
	    followed_ids = Relationship.where(lady_doctor_id: @lady_doctor.id).pluck(:male_id)
      @males = Male.where(id: followed_ids).all
    else
      render 'waiting'
    end

    if @lady_doctor.profile_image_id
      image_id = @lady_doctor.profile_image_id
      @lady_doctor_post = LadyDoctorPost.find(image_id)
    end
  end

  

  def show
    if @lady_doctor.profile_image_id
      image_id = @lady_doctor.profile_image_id
      @lady_doctor_post = LadyDoctorPost.find(image_id)
      @lady_doctor_posts = @lady_doctor.lady_doctor_posts.order(created_at: :desc).all
    else
      @lady_doctor_posts = @lady_doctor.lady_doctor_posts.order(created_at: :desc).all
    end
  end


  
  def edit
  end



  def update
    respond_to do |format|
      if @lady_doctor.update(lady_doctor_params)
        format.html { redirect_to @lady_doctor, notice: 'LadyDoctor was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @lady_doctor.errors, status: :unprocessable_entity }
      end
    end
  end



  def profile_update
    @lady_doctor_post = LadyDoctorPost.find(params[:id])
    @lady_doctor.profile_image_id = @lady_doctor_post.id

    respond_to do |format|
      if @lady_doctor.save
        format.html { redirect_to lady_doctor_path(id: @lady_doctor.id), notice: 'LadyDoctor was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @lady_doctor.errors, status: :unprocessable_entity }
      end
    end
  end



  def destroy
    @lady_doctor.destroy
    respond_to do |format|
      format.html { redirect_to new_lady_doctor_session_path, notice: 'あなたのアカウントは削除しました' }
      format.json { head :no_content }
    end
  end



  def follow_show
    if @male.profile_image_id
      image_id = @male.profile_image_id
      @male_post = MalePost.find(image_id)
    end
    @male_posts = @male.male_posts.order(created_at: :desc).all
  end



  def sending?(male)
    sending_likes.find_by(male_id: male.id)
  end




  private
  
  def lady_doctor_params
    params.require(:lady_doctor).permit(:name, :email, :doctor_number, :age, :sex, :school, :work, :annual_income, :password, :password_confirmation, :confirm_state, :profile_image_id)
  end

  def set_lady_doctor    
    @lady_doctor = current_lady_doctor || LadyDoctor.find(params[:id])
  end

  def sign_in?
    current_lady_doctor.confirm_state?
  end

  def blocked?
    @male = Male.find(params[:id])
    @lady_doctor = LadyDoctor.find(params[:lady_doctor_id])
    if MaleBlock.where(male_id: @male.id, lady_doctor_id: @lady_doctor.id).any?
      redirect_to lady_doctors_path
    end
  end



end

app/helpers/lady_doctors_helper.rb
module LadyDoctorsHelper
  
end

app/views/lady_doctors/_block.html.erb
<%= link_to "Block", lady_doctor_blocks_path( lady_doctor_id: lady_doctor.id, id: male.id), method: :post %>

app/views/lady_doctors/_block_form.html.erb
<div id="block_form">
  <% if lady_doctor.blocking?(male) %>
    <%= render partial: 'unblock', locals: {male: male, lady_doctor: lady_doctor} %>
  <% else %>
    <%= render partial: 'block', locals: {male: male, lady_doctor: lady_doctor} %>
  <% end %>
</div>

app/views/lady_doctors/_form.html.erb
<div class="row">
  <div class="span6 offset3"> 

    <%= form_for(@lady_doctor) do |f| %>
      <% if @lady_doctor.errors.any? %>
       <div id="error_explanation">
         <h2><%= pluralize(@lady_doctor.errors.count, "error") %> prohibited this male from being saved:</h2>

         <ul>
         <% @lady_doctor.errors.full_messages.each do |message| %>
          <li><%= message %></li>
         <% end %>
         </ul>
       </div>
    <% end %>
      
    
      <div class="field">
        <%= f.label :sex %><br>
        <%= f.select :sex, [["女", "female"],["男", "male"]]   %>
      </div>
      <div class="field">
        <%= f.label :name %><br>
        <%= f.text_field :name %>
      </div>
      
      <div class="field">
        <%= f.label :age %><br>
        <%= f.text_field :age %>
      </div>
      <div class="field">
        <%= f.label :school %><br>
        <%= f.text_field :school %>
      </div>
      <div class="field">
        <%= f.label :work %><br>
        <%= f.text_field :work %>
      </div>
      <div class="field">
        <%= f.label :annual_income %><br>
        <%= f.select :annual_income, [["200万~400万", "0"], ["400万~600万", "1"],["600万~800万", "2"], ["800万~1000万", "3"], ["1000万~2000万", "4"], ["2000万以上", "5"]] %>
      </div>
      <!--div class="field"-->
        <%#= f.label :image %><br>
        <%#= f.file_field :image %>
      <!--/div-->
      
      <div class="actions">
        <%= f.submit "登録", class: "btn btn-large btn-primary" %>
      </div>
    <% end %>

 </div>
</div>

app/views/lady_doctors/_like.html.erb
<%= link_to "Like", likes_path(id: male.id), method: :post %>

app/views/lady_doctors/_like_form.html.erb
<div id="like_form">
  <% if lady_doctor.sending?(male) %>
    <%= render partial: 'unlike', locals: {male: male, lady_doctor: lady_doctor} %>
  <% else %>
    <%= render partial: 'like', locals: {male: male} %>
  <% end %>
</div>

app/views/lady_doctors/_unblock.html.erb
<%= link_to "Unblock", lady_doctor_block_path(lady_doctor_id: lady_doctor.id, male_id: male.id, id: LadyDoctorBlock.find_by(male_id: male.id, lady_doctor_id: lady_doctor.id).id), method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/lady_doctors/_unlike.html.erb
<%= link_to "Like Cancel", like_path(male_id: male.id, id: lady_doctor.id), method: :delete, data: { confirm: 'Are you sure?' } %>

<%#= link_to "Like", likes_path(id: male.id), method: :post %>

app/views/lady_doctors/edit.html.erb
<div class="container">

<h1 class="notification">Editing user</h1>

<div class="item">

<%= render 'form' %> <!--partialを呼び込む -->

</div>

<br>

<%= link_to 'Back', lady_doctor_path(id: @lady_doctor.id) %> 
<%= link_to("Delete", lady_doctor_path(id: @lady_doctor.id) , method: :delete, data: { confirm: "Are you sure?" }) %>

</div>

app/views/lady_doctors/follow_show.html.erb
<div class="container">
  <div class="clearfix userWrapper" >
    <div class="box_left myprofile">

       <% if @male_post != nil %>
        <% if @male_post.image? %>
　　       <%= image_tag @male_post.image.thumb.url %>
        <% else %>
　　       <%= image_tag 'noimage.gif' %>
        <% end %>
      <% else %>
        <%= image_tag 'noimage.gif' %>
      <% end %>
    </div>
    <!-- 画像 -->

    <div class="box_left profile">
      <span class="default">名前:</span><span class="unique"><%= @male.name %></span>
      <% if @male.age != nil %>
      <span class="default">   年齢: </span><span class="unique"><%= @male.age %></span><br>
      <% end %>
      <% if @male.work != nil %>
      <span class="default">仕事: </span><span class="unique"><%= @male.work %></span>
      <% end %>
      <% if @male.annual_income != nil %>
      <span class="default">年収: </span><span class="unique"><%= @male.annual_income %></span><br>
      <% end %>
      <br><%= Relationship.where(male_id: @male.id).count %></span><span class="default">  Followings</span>
    </div>
    <!-- プロフィール -->

  </div>
  <!--  clearfix userWrapper  -->

  <div class= "userPostWrapper">
    <% @male_posts.each do |male_post| %>
      <div class="item">
        <div class="main">
          <div class ="clearfix" >
            <div class="box_left ladyprofile">
              <% if @male_post != nil %>
                <% if @male_post.image? %>
                  <%= image_tag @male_post.image.thumb.url %>
                <% else %>
                  <%= image_tag 'noimage.gif' %>
                <% end %>
              <% else %>
                <%= image_tag 'noimage.gif' %>
              <% end %>
            </div>

            <div class="box_left profile">
              <span class="unique"><%= @male.name %></span>  <span class="default">Posted my photo.</span>  <br>
              <span class="default">posted at </span> <span class="unique"><%= male_post.created_at %></span><br>
              <%= Relationship.where(male_id: @male.id).count %></span><span class="default">  Followings</span>

            </div>
          </div>
          <!--clearfix-->

          <div class="userContent">
            <%= male_post.content %>
          </div>

<div class="ladyimage">

          <% if male_post.image? %>
            <%= image_tag male_post.image.url %>
          <% else %>
            <%= image_tag 'noimage.gif' %>
          <% end %>
</div>
      </div>
      <!-- main -->
      </div><!--item -->
    <% end %> 
     </div> 
  <!--userPostWrapper -->
  
<%= link_to 'Back', lady_doctors_path %>

</div>

app/views/lady_doctors/index.html.erb
<div class="container">
  <% if @lady_doctor.age.nil? && @lady_doctor.profile_image_id.nil? %>
    <span class="notification">まずはMyPageから自分のプロフィールを編集してね！<br>それができたら、投稿をしてプロフィール画像を設定してね</span>
  <% elsif !@lady_doctor.age.nil? && @lady_doctor.profile_image_id.nil? %>
    <span class="notification">投稿をしてプロフィール画像を設定してね</span>
  <% elsif @lady_doctor.age.nil? && !@lady_doctor.profile_image_id.nil? %>
    <span class="notification">MyPageから自分のプロフィールを編集してね！</span>
  <% else %>
    <span class="notification">気に入った男性をlikeしてみよう！</span>
  <% end %>
  <div class="clearfix userWrapper">
    <div class="box_left ladyprofile">
      <% if @lady_doctor_post != nil %>
        <% if @lady_doctor_post.image? %>
      <%= image_tag @lady_doctor_post.image.thumb.url %>
        <% else %>
         <%= image_tag 'noimage.gif' %>
        <% end %>
      <% else %>
        <%= image_tag 'noimage.gif' %>
      <% end %>
    </div>
    <!-- box_left ladyprofile -->
    <div class="box_left profile">
      <span class="default">名前：</span><span class="unique"><%= link_to "#{@lady_doctor.name}", @lady_doctor %></span><br>
      <span class="default">MyPosts:</span> <%= @lady_doctor.lady_doctor_posts.count %> | <%= Relationship.where(lady_doctor_id: @lady_doctor.id).count %></span><span class="default">  Followers</span><br>
    </div>
  </div>
  <!-- clearfix userWrapper -->



      <%#= profile_image_for @male %>
      
      <%#= puts @males %>
  <div class="userPostWrapper">
    <% if @males.any? %>
      <h2 class="notification">Followしてきた男性一覧</h2>
        
          <% @males.each do |male| %>
            <div class="item">
            <div class="userWrapper_extra"> 
              <div class ="clearfix">
                <div class="box_left myprofile follow">
                  <% if male.profile_image_id %>
                    <%= image_tag MalePost.find(male.profile_image_id).image.thumb.url %>
                  <% else %>
                    <%= image_tag 'noimage.gif' %>
                  <% end %>
                </div>
                <div class="box_left followprofile">
                  <span class="default">名前: </span><span class="unique"><%= link_to "#{male.name}", follower_path(lady_doctor_id: @lady_doctor.id, id: male.id) %></span><br>
                  <%= Relationship.where(male_id: male.id).count %></span><span class="default">  Followings</span>
                  <%= render partial: 'block_form', locals: {male: male, lady_doctor: @lady_doctor} %>
                </div>
              </div>
              <!-- clearfix -->

              <div class="_18--"></div>
              <div class="additionpost clearfix">
                <div class="additionleft"><%= render partial: 'like_form', locals: {male: male, lady_doctor: @lady_doctor} %>
                </div>
              </div>
              <!-- additionpost -->
            </div>
            <!--  userWrapper_extra -->
            </div>
        <!-- item -->
          <% end %>
        
    <% end %>
  </div>
  <!-- userPostWrapper -->
 
<%= link_to 'ログアウト', destroy_lady_doctor_session_path, method: :delete %>

</div>

app/views/lady_doctors/show.html.erb
<div class="container">
  <% if @lady_doctor.age.nil? && @lady_doctor.profile_image_id.nil? %>
    <span class="notification">自分のプロフィールを編集してね！<br>それができたら、投稿をしてプロフィール画像を設定してね</span>
  <% elsif !@lady_doctor.age.nil? && @lady_doctor.profile_image_id.nil? %>
    <span class="notification">プロフィール編集したね！<br>次は投稿をしてプロフィール画像を設定してね</span>
  <% elsif @lady_doctor.age.nil? && !@lady_doctor.profile_image_id.nil? %>
    <span class="notification">自分のプロフィールを編集してね！</span>
  <% end %>
  <div class="clearfix userWrapper" >
    <div class="box_left ladyprofile">
      <% if @lady_doctor_post != nil %>
        <% if @lady_doctor_post.image? %>
         <%= image_tag @lady_doctor_post.image.thumb.url %>
        <% else %>
         <%= image_tag 'noimage.gif' %>
        <% end %>
      <% else %>
        <%= image_tag 'noimage.gif' %>
      <% end %>
    </div>

    <div class="box_left profile">
       <span class="default">名前:</span><span class="unique"><%= @lady_doctor.name %></span>
       <% if @lady_doctor.age != nil %>
      <span class="default">   年齢: </span><span class="unique"><%= @lady_doctor.age %></span><br>
      <% end %>
      <% if @lady_doctor.work != nil %>
      <span class="default">仕事: </span><span class="unique"><%= @lady_doctor.work %></span>
      <% end %>
      <% if @lady_doctor.annual_income != nil %>
      <span class="default">年収: </span><span class="unique"><%= @lady_doctor.annual_income %></span><br>
      <% end %>
       <br><%= Relationship.where(lady_doctor_id: @lady_doctor.id).count %></span><span class="default">  Followers</span><br>
       <%= link_to 'Edit My Profile', edit_lady_doctor_path(id: @lady_doctor)  %><br>
    </div>

  </div>
  <!--  clearfix userWrapper  -->


  <%= link_to 'New Post',  new_lady_doctor_lady_doctor_post_path(lady_doctor_id: @lady_doctor.id) %> 


  <div class= "userPostWrapper">
    <% @lady_doctor_posts.each do |lady_doctor_post| %>
      <div class="item">
        <div class="main">
          <div class ="clearfix" >
            <div class="box_left ladyprofile">
              <% if @lady_doctor_post != nil %>
                <% if @lady_doctor_post.image? %>
                 <%= image_tag @lady_doctor_post.image.thumb.url %>
                <% else %>
                 <%= image_tag 'noimage.gif' %>
                <% end %>
              <% else %>
                <%= image_tag 'noimage.gif' %>
              <% end %>
            </div>

            <div class="box_left profile">
              <span class="unique"><%= @lady_doctor.name %></span>  <span class="default">Posted my photo.</span>  <br>
              <span class="default">posted at </span> <span class="unique"><%= lady_doctor_post.created_at %></span> <br>
              <%= Relationship.where(lady_doctor_id: lady_doctor_post.lady_doctor.id).count %></span><span class="default">  Followers</span><br>
            </div>
          </div>
          <!-- clearfix -->

          <div class="userContent">
            <%= lady_doctor_post.content %>
          </div>


<div class="image">
          <% if lady_doctor_post.image? %>
　　         <%= image_tag lady_doctor_post.image.url %>
　        <% else %>
　　         <%= image_tag 'noimage.gif' %>
　        <% end %>
</div>
        </div>
        <!--main-->

        <div class="_18--"></div>
        <div class="additionpost">
        <%= MalePostComment.where(lady_doctor_post_id: lady_doctor_post.id).count %></span><span class="default"> Comments</span><br>
        <%= link_to 'Show', lady_doctor_lady_doctor_post_path(lady_doctor_id: @lady_doctor.id, id: lady_doctor_post.id) %>
        <%= link_to 'Edit', edit_lady_doctor_lady_doctor_post_path(lady_doctor_id: @lady_doctor.id, id: lady_doctor_post.id) %>
        <%= link_to 'Delete', lady_doctor_lady_doctor_post_path(lady_doctor_id: @lady_doctor.id, id: lady_doctor_post.id), method: :delete, data: { confirm: 'Are you sure?' } %>
        <%= link_to 'これをプロフィール画像にする', lady_doctor_image_path(lady_doctor_id: @lady_doctor.id, id: lady_doctor_post.id), method: :post %>
      </div>
     </div>
     <!-- item -->
    <% end %>
</div>
<!-- userPostErapper --> 


<%#= link_to 'Edit My Profile', edit_my_thread_path(@my_thread) %> 
<%= link_to 'Back', lady_doctors_path %>

</div>

app/views/lady_doctors/waiting.html.erb
<div class="container">

<h2 class="notification">承認中です！</h2>
<p class="notification">少々おまちください^^</p>

</div>