config/routes.rb
Rails.application.routes.draw do
  devise_for :males, controllers:{
    sessions:        'males/sessions',
    passwords:       'males/passwords',
    registrations:   'males/registrations'
  }
  devise_for :lady_doctors, controllers:{
    sessions:        'lady_doctors/sessions',
    passwords:       'lady_doctors/passwords',
    registrations:   'lady_doctors/registrations'
  }
  devise_for :admins, controllers:{
    sessions:        'admins/sessions',
    passwords:       'admins/passwords',
    registrations:   'admins/registrations'
  }
  

  devise_scope :male do
      get "/", :to => "males/sessions#new"
  end

 
  

  resources :admins, only: [:index]
  get "admins/confirm/:id" => "admins#confirm"

  get "males/:male_id/lady_doctor_posts/:id/comment" => "male_post_comments#new", as: :new_male_post_comment
  post "males/:male_id/profile_image/:id" => 'males#profile_update', as: :male_image
  get 'males/:male_id/lady_doctor_posts/:id' => 'males#lady_doctor_posts_show', as: :lady_doctor_posts_show
  get 'males/:male_id/lady_doctor/:id' => 'males#lady_doctor_index', as: :lady_doctor_index

  resources :males do
    member do
      get :following
      get :unfollowing, only: [:index]      
    end
    resources :male_posts
  end
  
  get 'males/:male_id/following/lady_docotrs/:id' => 'males#following_index', as: :following_index
  get 'males/:male_id/unfollowing/lady_docotrs/:id' => 'males#unfollowing_index', as: :unfollowing_index

  resources :male_post_comments, except: [:new]
  

 
  

  resources :lady_doctors do
    resources :lady_doctor_posts
  end
  
  get "lady_doctors/:lady_doctor_id/lady_doctor_posts/:lady_doctor_post_id/follow_male/:id" => 'lady_doctor_posts#male_show', as: :commenter  

 
  get 'lady_doctors/:lady_doctor_id/follow_male/:id' => 'lady_doctors#follow_show', as: :follower
  post "lady_doctors/:lady_doctor_id/profile_image/:id" => 'lady_doctors#profile_update', as: :lady_doctor_image
  

  resources :relationships, path: "lady_doctors/:id/follow", only: [:create]
  resources :relationships, path: "lady_doctors/:lady_doctor_id/unfollow", only: [:destroy]

  resources :likes, path: "males/:id/like", only: [:create]
  resources :likes, path: "males/:male_id/unlike", only: [:destroy]

  resources :male_blocks, path: "males/:male_id/lady_doctors/:id/block", only: [:create]
  resources :male_blocks, path: "males/:male_id/lady_doctors/:lady_doctor_id/unblock", only: [:destroy]
  
  resources :lady_doctor_blocks, path: "lady_doctors/:lady_doctor_id/males/:id/block", only: [:create]
  resources :lady_doctor_blocks, path: "lady_doctors/:lady_doctor_id/males/:male_id/unblock", only: [:destroy]

  
  

end

app/models/lady_doctor_post.rb
class LadyDoctorPost < ActiveRecord::Base
	belongs_to :lady_doctor
	has_many :male_post_comments

  validates :lady_doctor_id, presence: true
  validates :content, presence: true

	mount_uploader :image, ImageUploader
end

app/controllers/lady_doctor_posts_controller.rb
class LadyDoctorPostsController < ApplicationController
	before_action :authenticate_lady_doctor!
	before_action :blocked?, only: [:male_show] 
	before_action :set_lady_doctor_post, only: [:show, :edit, :update, :destroy]
	before_action :set_lady_doctor, only: [:new, :create, :index, :update, :destroy]

	def index
      #@lady_doctor_post = LadyDoctorPost.all
	end
    
	def new
	  #@lady_doctor.transaction do
	    @lady_doctor_post = LadyDoctorPost.new
	  #end
	  
	  #rescue => e
	  #render  :text => e.message	
	end

	def create
	  @lady_doctor_post = @lady_doctor.lady_doctor_posts.build(lady_doctor_post_params)

	  respond_to do |format|
	  	#saveされたら showへ飛ばす。されなかったらもう一度new画面に戻る
        if @lady_doctor_post.save
          format.html { redirect_to lady_doctor_path(id: @lady_doctor.id), notice: 'Post was successfully created.' }
          format.json { render :show, status: :created, location: lady_doctor_path(id: @lady_doctor.id) }
        else
          format.html { render :new }
          format.json { render json: @lady_doctor_post.errors, status: :unprocessable_entity }
        end
      end
	end

	def show
	  @lady_doctor = LadyDoctor.find(params[:lady_doctor_id])
	  if @lady_doctor.profile_image_id
        image_id = @lady_doctor.profile_image_id
        @post = LadyDoctorPost.find(image_id)
      end
      @male
	  @lady_doctor_post = LadyDoctorPost.find(params[:id])
	  @male_post_comments = MalePostComment.where(lady_doctor_post_id: @lady_doctor_post.id).order(created_at: :desc)
	end

	def edit
	  @lady_doctor = @lady_doctor_post.lady_doctor(params[:id])
	end

	def update
      respond_to do |format|
	  	#saveされたら showへ飛ばす。されなかったらもう一度new画面に戻る
        if @lady_doctor_post.update(lady_doctor_post_params)
          format.html { redirect_to @lady_doctor, notice: 'Post was successfully updated.' }
          format.json { render :show, status: :created, location: @lady_doctor }
        else
          format.html { render :new }
          format.json { render json: @lady_doctor_post.errors, status: :unprocessable_entity }
        end
      end	  

	end

	def destroy
	  @lady_doctor_post.destroy
	  respond_to do |format|
        format.html { redirect_to @lady_doctor, notice: 'Post was successfully destroyed.' }
        format.json { head :no_content }
      end
	end

    def male_show
      if @male.profile_image_id
        image_id = @male.profile_image_id
        @male_post = MalePost.find(image_id)
      end
      @male_posts = @male.male_posts.order(created_at: :desc).all
    end



	private

	#male_postのcontentのみ更新可能
	def lady_doctor_post_params
	  params.require(:lady_doctor_post).permit(:content, :image)
	end

	def set_lady_doctor_post
	  @lady_doctor_post = LadyDoctorPost.find(params[:id])
	end

	def set_lady_doctor
	  @lady_doctor = current_lady_doctor
	end

	def blocked?
      @male = Male.find(params[:id])
      @lady_doctor = LadyDoctor.find(params[:lady_doctor_id])
      if MaleBlock.where(male_id: @male.id, lady_doctor_id: @lady_doctor.id).any?
        redirect_to @lady_doctor
      end
    end


end

app/helpers/lady_doctor_posts_helper.rb
module LadyDoctorPostsHelper
end

app/views/lady_doctor_posts/_block.html.erb
<%= link_to "Block", lady_doctor_blocks_path(lady_doctor_id: lady_doctor.id, id: male.id), method: :post %>

app/views/lady_doctor_posts/_block_form.html.erb
<div id="block_form">
  <% if lady_doctor.blocking?(male) %>
    <%= render partial: 'unblock', locals: {male: male, lady_doctor: lady_doctor} %>
  <% else %>
    <%= render partial: 'block', locals: {male: male, lady_doctor: lady_doctor} %>
  <% end %>
</div>

app/views/lady_doctor_posts/_form.html.erb
<%= form_for([@lady_doctor,@lady_doctor_post]) do |f| %>
  <% if @lady_doctor_post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lady_doctor_post.errors.count, "error") %> prohibited this lady_doctor_post from being saved:</h2>

      <ul>
      <% @lady_doctor_post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="hidden">
    <%= f.hidden_field :lady_doctor_id, :value => @lady_doctor.id %>
  </div>
  <div class="field">
    <%= f.label :image %>
　　 <%= f.file_field :image %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lady_doctor_posts/_unblock.html.erb
<%= link_to "Unblock", lady_doctor_block_path(lady_doctor_id: lady_doctor.id, male_id: male.id, id: LadyDoctorBlock.find_by(male_id: male.id, lady_doctor_id: lady_doctor.id).id), method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/lady_doctor_posts/edit.html.erb
<div class="container">

<h1 class="notification">Edit post</h1>

<div class="item">

<%= render 'form' %>

</div>

<br>

<%= link_to 'Back', @lady_doctor %> 

</div>

app/views/lady_doctor_posts/index.html.erb
<!--　使うか？　-->

<h1>TimeLine</h1>

<table>
  <thead>
    <tr>
	  <th>content:</th>
	  <th colspan = "3" ></th>
	</tr>
  </thead>
  <tbody>
  	<% @lady_doctor_post.each do |lady_doctor_post| %>
  	 <tr>
  	  <td><%= lady_doctor_post.content %></td>
  	  <td><%= link_to 'Show', lady_doctor_post %></td>
  	  <td><%= link_to 'Edit', edit_lady_doctor_post_path(id: lady_doctor_post.id) %></td>
  	  <td><%= link_to 'Delete', lady_doctor_post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  	 </tr>
  	<% end %> 
  </tbody>
</table> 

<br>

app/views/lady_doctor_posts/male_show.html.erb
<div class="container">
  <div class="clearfix userWrapper" >
    <div class="box_left myprofile">

       <% if @male_post != nil %>
        <% if @male_post.image? %>
　　       <%= image_tag @male_post.image.thumb.url %>
        <% else %>
　　       <%= image_tag 'noimage.gif' %>
        <% end %>
      <% else %>
        <%= image_tag 'noimage.gif' %>
      <% end %>
    </div>
    <!-- 画像 -->

    <div class="box_left profile">
      <span class="default">名前:</span><span class="unique"><%= @male.name %></span>
      <% if @male.age != nil %>
      <span class="default">   年齢: </span><span class="unique"><%= @male.age %></span><br>
      <% end %>
      <% if @male.work != nil %>
      <span class="default">仕事: </span><span class="unique"><%= @male.work %></span>
      <% end %>
      <% if @male.annual_income != nil %>
      <span class="default">年収: </span><span class="unique"><%= @male.annual_income %></span><br>
      <% end %>
      <br><%= Relationship.where(male_id: @male.id).count %></span><span class="default">  Followings</span>
    </div>
    <!-- プロフィール -->

  </div>
  <!--  clearfix userWrapper  -->

  <div class= "userPostWrapper">
    <% @male_posts.each do |male_post| %>
      <div class="item">
        <div class="main">
          <div class ="clearfix" >
            <div class="box_left ladyprofile">
              <% if @male_post != nil %>
                <% if @male_post.image? %>
                  <%= image_tag @male_post.image.thumb.url %>
                <% else %>
                  <%= image_tag 'noimage.gif' %>
                <% end %>
              <% else %>
                <%= image_tag 'noimage.gif' %>
              <% end %>
            </div>

            <div class="box_left profile">
              <span class="unique"><%= @male.name %></span>  <span class="default">Posted my photo.</span>  <br>
              <span class="default">posted at </span> <span class="unique"><%= male_post.created_at %></span><br>
              <%= Relationship.where(male_id: @male.id).count %></span><span class="default">  Followings</span>

            </div>
          </div>
          <!--clearfix-->

          <div class="userContent">
            <%= male_post.content %>
          </div>

<div class="ladyimage">

          <% if male_post.image? %>
            <%= image_tag male_post.image.url %>
          <% else %>
            <%= image_tag 'noimage.gif' %>
          <% end %>
</div>
      </div>
      <!-- main -->
      </div><!--item -->
    <% end %> 
     </div> 
  <!--userPostWrapper -->
  
<%= link_to 'MyPageに戻る', lady_doctor_path(id: @lady_doctor.id) %>

</div>

app/views/lady_doctor_posts/new.html.erb
<div class="container">

<h1 class="notification">New Post</h1>

<div class="item">

<%= render 'form' %>

</div>

<br>

<%= link_to 'Back', @lady_doctor %> 

</div>

app/views/lady_doctor_posts/show.html.erb
<div class="container">
 <div class="item">
    <div class="main">
      <div class ="clearfix" >
        <div class="box_left ladyprofile">
          <% if @post != nil %>
            <% if @post.image? %>
             <%= image_tag @post.image.thumb.url %>
            <% else %>
          <%= image_tag 'noimage.gif' %>
            <% end %>
          <% else %>
            <%= image_tag 'noimage.gif' %>
          <% end %>
        </div>
        <div class="box_left profile">
          <span class="unique"><%= @lady_doctor.name %> </span><span class="default">posted my photo.</span> <br>
          <span class="default">Posted at</span> <span class="unique"><%= @lady_doctor_post.created_at %></span><br>
          <%= Relationship.where(lady_doctor_id: @lady_doctor.id).count %></span><span class="default">  Followings</span><br>
        </div>
      </div>
      <!-- clearfix -->

      <div class="userContent">
        <%= @lady_doctor_post.content %>
      </div>
        

<div class="ladyimage">
      <% if @lady_doctor_post.image? %>
        <%= image_tag @lady_doctor_post.image.url %>
      <% else %>
        <%= image_tag 'noimage.gif' %>
      <% end %>
</div>

    </div>
    <!-- main -->

    
    <div class="additionpost">
      <% if @male_post_comments.any? %>
      <div class="_18--"></div>
        <strong>コメント一覧</strong><br>
        <% @male_post_comments.each do |male_post_comment| %>
          <% if male_post_comment.male.profile_image_id %>
            <%= image_tag MalePost.find(male_post_comment.male.profile_image_id).image.thumb.url %>
          <% else %>
            <%= image_tag 'noimage.gif' %>
          <% end %>
          <span class="default">名前：</span><span class="unique"><%= link_to "#{male_post_comment.male.name}",  commenter_path(lady_doctor_id: @lady_doctor.id, lady_doctor_post_id: @lady_doctor_post.id, id: male_post_comment.male.id) %></span> |
          <%= male_post_comment.comment %>

          <%= render partial: 'lady_doctors/block_form', locals: {male: male_post_comment.male, lady_doctor: @lady_doctor} %>
          

          <br>
        <% end %>
      <% end %>
    </div>
    <!-- additionpost -->
  </div>
  <!-- item -->
<%#= link_to 'New Comment', new_male_post_comment_path(male_id: male.id, id: @lady_doctor_post.id) %> <br>

<%= link_to 'Back', @lady_doctor %>
</div>

</div>