config/routes.rb
Rails.application.routes.draw do
  devise_for :males, controllers:{
    sessions:        'males/sessions',
    passwords:       'males/passwords',
    registrations:   'males/registrations'
  }
  devise_for :lady_doctors, controllers:{
    sessions:        'lady_doctors/sessions',
    passwords:       'lady_doctors/passwords',
    registrations:   'lady_doctors/registrations'
  }
  devise_for :admins, controllers:{
    sessions:        'admins/sessions',
    passwords:       'admins/passwords',
    registrations:   'admins/registrations'
  }
  

  devise_scope :male do
      get "/", :to => "males/sessions#new"
  end

 
  

  resources :admins, only: [:index]
  get "admins/confirm/:id" => "admins#confirm"

  get "males/:male_id/lady_doctor_posts/:id/comment" => "male_post_comments#new", as: :new_male_post_comment
  post "males/:male_id/profile_image/:id" => 'males#profile_update', as: :male_image
  get 'males/:male_id/lady_doctor_posts/:id' => 'males#lady_doctor_posts_show', as: :lady_doctor_posts_show
  get 'males/:male_id/lady_doctor/:id' => 'males#lady_doctor_index', as: :lady_doctor_index

  resources :males do
    member do
      get :following
      get :unfollowing, only: [:index]      
    end
    resources :male_posts
  end
  
  get 'males/:male_id/following/lady_docotrs/:id' => 'males#following_index', as: :following_index
  get 'males/:male_id/unfollowing/lady_docotrs/:id' => 'males#unfollowing_index', as: :unfollowing_index

  resources :male_post_comments, except: [:new]
  

 
  

  resources :lady_doctors do
    resources :lady_doctor_posts
  end
  
  get "lady_doctors/:lady_doctor_id/lady_doctor_posts/:lady_doctor_post_id/follow_male/:id" => 'lady_doctor_posts#male_show', as: :commenter  

 
  get 'lady_doctors/:lady_doctor_id/follow_male/:id' => 'lady_doctors#follow_show', as: :follower
  post "lady_doctors/:lady_doctor_id/profile_image/:id" => 'lady_doctors#profile_update', as: :lady_doctor_image
  

  resources :relationships, path: "lady_doctors/:id/follow", only: [:create]
  resources :relationships, path: "lady_doctors/:lady_doctor_id/unfollow", only: [:destroy]

  resources :likes, path: "males/:id/like", only: [:create]
  resources :likes, path: "males/:male_id/unlike", only: [:destroy]

  resources :male_blocks, path: "males/:male_id/lady_doctors/:id/block", only: [:create]
  resources :male_blocks, path: "males/:male_id/lady_doctors/:lady_doctor_id/unblock", only: [:destroy]
  
  resources :lady_doctor_blocks, path: "lady_doctors/:lady_doctor_id/males/:id/block", only: [:create]
  resources :lady_doctor_blocks, path: "lady_doctors/:lady_doctor_id/males/:male_id/unblock", only: [:destroy]

  
  

end

app/models/male.rb
class Male < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  #do 'follow'
  #has_many :following_relationships, foreign_key: "male_id", class_name: "Relationship", dependent: :destroy
  has_many :following_relationships, foreign_key: "lady_doctor_id", class_name: "Relationship", dependent: :destroy
  has_many :followings, through: :following_relationships

  validates :name, presence: true  
  
  has_many :male_posts
  has_many :male_post_comments

  has_many :male_blocks

  def following?(lady_doctor)
    following_relationships.find_by(lady_doctor_id: lady_doctor.id)
  end

  def follow!(lady_doctor)
    following_relationships.create!(lady_doctor_id: lady_doctor.id)
  end

  def unfollow!(lady_doctor)
    following_relationships.find_by(lady_doctor_id: lady_doctor.id).destroy
  end

  def blocking?(lady_doctor)
    male_blocks.find_by(lady_doctor_id: lady_doctor.id) != nil
  end
  

end

app/controllers/males/confirmations_controller.rb
class Males::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/males/omniauth_callbacks_controller.rb
class Males::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when omniauth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/males/passwords_controller.rb
class Males::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/males/registrations_controller.rb
class Males::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]
before_filter :configure_permitted_parameters
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end
  #GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # You can put the params you want to permit in the empty array.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/males/sessions_controller.rb
class Males::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
     super
     #redirect_to new_male_session_path
  end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  def destroy
    p 'fuga'
    super
  end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end

  def after_sign_out_path_for(resource)
    case resource
    when :male
      p 'hoge'
      new_male_session_path
    when :lady_doctor
      new_lady_doctor_session_path
    #when Admin
    end
  end 
end

app/controllers/males/unlocks_controller.rb
class Males::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/males_controller.rb
class MalesController < ApplicationController
  before_action :authenticate_male!
  before_action :set_follow_ids, only: [:index, :unfollowing]
  before_action :set_male, only: [:index, :show, :edit, :update, :destroy, :unfollowing, :following, :profile_update, :following_index, :unfollowing_index]

	def index
    if @male.profile_image_id
      image_id = @male.profile_image_id
      @male_post = MalePost.find(image_id)
      @male_posts = @male.male_posts.order(created_at: :desc).all
    #else  
      #@male_posts = @male.male_posts.all
      
    else
      @male_posts = @male.male_posts.order(created_at: :desc).all
    end

    @title = "フォローしている女医の投稿"
    #@lady_doctorsのlady_doctor_postすべてをcreated_atが新しい順のfirstをとってくる
    #followしている女性all

    follow_ids = Relationship.where(male_id: @male.id).pluck(:lady_doctor_id)
    @lady_doctors = LadyDoctor.where(id: follow_ids)
    @lady_doctor_posts = LadyDoctorPost.where(lady_doctor_id: follow_ids).order(created_at: :desc).all
    @comments = Like.where(male_id: @male.id).pluck(:comment)
	end



  def edit
  end



  def update
    respond_to do |format|
      if @male.update(male_params)
        format.html { redirect_to @male, notice: 'Male was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @male.errors, status: :unprocessable_entity }
      end
    end
  end

  def following
    #@lady_doctorsのlady_doctor_postすべてをcreated_atが新しい順のfirstをとってくる
    #followしている女性all
    follow_ids = Relationship.where(male_id: @male.id).pluck(:lady_doctor_id)
    @lady_doctors = LadyDoctor.where(id: follow_ids).order(created_at: :desc).all
  end



  def following_index 
    @lady_doctor = LadyDoctor.find(params[:id])    
    if @lady_doctor.profile_image_id
      image_id = @lady_doctor.profile_image_id
      @lady_doctor_post = LadyDoctorPost.find(image_id)
      @lady_doctor_posts = @lady_doctor.lady_doctor_posts.order(created_at: :desc).all
    else
      @lady_doctor_posts = @lady_doctor.lady_doctor_posts.order(created_at: :desc).all
    end
    if LadyDoctorBlock.where(male_id: @male.id, lady_doctor_id: @lady_doctor.id).any?
      redirect_to following_male_path
    end
  end



  def unfollowing
    #followしてない女医を全部とってくる
    follow_ids = Relationship.where(male_id: @male.id).pluck(:lady_doctor_id)
    @lady_doctors = LadyDoctor.where.not(id: follow_ids).order(created_at: :desc).all
  end



  def unfollowing_index
    @lady_doctor = LadyDoctor.find(params[:id])
    if @lady_doctor.profile_image_id
      image_id = @lady_doctor.profile_image_id
      @lady_doctor_post = LadyDoctorPost.find(image_id)
      @lady_doctor_posts = @lady_doctor.lady_doctor_posts.order(created_at: :desc).all
    else
      @lady_doctor_posts = @lady_doctor.lady_doctor_posts.order(created_at: :desc).all
    end
  end



  def show
    if @male.profile_image_id
      image_id = @male.profile_image_id
      @male_post = MalePost.find(image_id)
      @male_posts = @male.male_posts.order(created_at: :desc).all
    #else  
      #@male_posts = @male.male_posts.all
      
    else
      @male_posts = @male.male_posts.order(created_at: :desc).all
    end
  end
  


  def destroy
    @male.destroy
    respond_to do |format|
      format.html { redirect_to new_male_session_path, notice: 'Male user was successfully destroyed.' }
      format.json { head :no_content }
    end
  end



  def profile_update
    @male_post = MalePost.find(params[:id])
    @male.profile_image_id = @male_post.id

    respond_to do |format|
      if @male.save
        format.html { redirect_to male_path(id: @male.id), notice: 'Profile Image was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @male.errors, status: :unprocessable_entity }
      end
    end
  end



  def lady_doctor_posts_show
    @male = Male.find(params[:male_id])
    @lady_doctor_post = LadyDoctorPost.find(params[:id])
    @lady_doctor = @lady_doctor_post.lady_doctor
    @male_post_comments = MalePostComment.where(lady_doctor_post_id: @lady_doctor_post.id, male_id: @male.id).order(created_at: :desc).all
    if LadyDoctorBlock.where(male_id: @male.id, lady_doctor_id: @lady_doctor.id).any?
      redirect_to males_path
    end
  end


  
  def lady_doctor_index
    #@lady_doctor_post = LadyDoctorPost.find(params[:lady_doctor_post_id])
    @male = Male.find(params[:male_id])
    @lady_doctor = LadyDoctor.find(params[:id])
    @lady_doctor_posts = @lady_doctor.lady_doctor_posts.order(created_at: :desc).all
    if LadyDoctorBlock.where(male_id: @male.id, lady_doctor_id: @lady_doctor.id).any?
      redirect_to males_path
    end
  end




  def following?(lady_doctor)
    following_relationships.find_by(lady_doctor_id: lady_doctor.id)
  end

  def follow!(lady_doctor)
    following_relationships.create!(lady_doctor_id: lady_doctor.id)
  end

  def unfollow!(lady_doctor)
    following_relationships.find_by(lady_doctor_id: lady_doctor.id).destroy
  end
  




  private
  
  #
  def male_params
    params.require(:male).permit(:name, :email, :age, :sex, :school, :work, :annual_income, :password, :password_confirmation)
  end

  def set_male    
    @male = current_male || Male.find(params[:id])
  end

  def set_follow_ids
    follow_ids = Relationship.where(male_id = current_male.id).pluck(:lady_doctor_id)
  end

end

app/helpers/males_helper.rb
module MalesHelper
  def sign_in(male)
    remember_token = Male.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    male.update_attribute(:remember_token, Male.encrypt(remember_token))
    self.current_male = male
  end

  def signed_in?
    !current_male.nil?
  end

  def current_male
    remember_token = Male.encrypt(cookies[:remember_token])
    @current_male ||= Male.find_by(remember_token: remember_token)
  end

  def current_male?(male)
    male == current_male
  end

  def current_male=(male)
    @current_male = male
  end

  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end

  def signed_in_user
      redirect_to signin_url, notice: "Please sign in." unless signed_in?
  end

end

app/views/males/_block.html.erb
<%= link_to "Block", male_blocks_path(male_id: male.id, id: lady_doctor.id), method: :post %>

app/views/males/_follow.html.erb
<%= link_to "Follow", relationships_path(id: lady_doctor.id), method: :post %>

app/views/males/following.html.erb
<div class="container">

<h4>投稿にイケてるコメントをしてLikeを自分に引き寄せろ！</h4>


<h3 class="notification">フォローしてる女医たち</h3>

   <div class="userPostWrapper">
    <% @lady_doctors.each do |lady_doctor| %>
    <div class="userWrapper_unfollow"> 
          <div class ="clearfix">
              <div class="box_left myprofile follow">
                <% if lady_doctor.profile_image_id %>
                  <%= image_tag LadyDoctorPost.find(lady_doctor.profile_image_id).image.thumb.url %>
                <% else %>
                  <%= image_tag 'noimage.gif' %>
                <% end %>
              </div> 


              <div class="box_left followprofile">
                  <span class="unique"><%= link_to "#{lady_doctor.name}", following_index_path(male_id: @male.id, id: lady_doctor.id) %></span> 
                   <span class="default">年齢：</span><span class="unique"><%= lady_doctor.age %></span><br>
                   <%= Relationship.where(lady_doctor_id: lady_doctor.id).count %></span><span class="default">  Followers</span><br>





                   <%= render partial: 'block_form', locals: {male: @male, lady_doctor: lady_doctor} %>
                




              </div>
              
          </div>
            <!--clearfix-->

            

      </div>
      <!-- userWrapper_unfollow-->
            
        

        
    <% end %> 
  </div> 
  <!--userPostWrapper -->
<%= link_to 'フォローしてない女医一覧', unfollowing_male_path(id: @male.id) %><br>
<%= link_to 'Back', males_path %>
</div>

app/views/males/index.html.erb
<div class="container">
  <div class="notification">
  <% if @male.age.nil? && @male.profile_image_id.nil? %>
    <span class="notification">まずはMyPageから自分のプロフィールを編集してね！<br>それができたら、投稿をしてプロフィール画像を設定してね</span>
  <% elsif !@male.age.nil? && @male.profile_image_id.nil? %>
    <span class="notification">投稿をしてプロフィール画像を設定してね</span>
  <% elsif @male.age.nil? && !@male.profile_image_id.nil? %>
    <span class="notification">MyPageから自分のプロフィールを編集してね！</span>
  <% else %>
    <span class="notification">気に入った女医をフォローして、投稿にコメントしてアピールしよう！</span><br>
  <% end %>
  </div>



  <div class="clearfix userWrapper" >
    <div class="box_left myprofile">
      <% if @male_post != nil %>
        <% if @male_post.image? %>
         <%= image_tag @male_post.image.thumb.url %>
        <% else %>
         <%= image_tag 'noimage.gif' %>
        <% end %>
      <% else %>
        <%= image_tag 'noimage.gif' %>
      <% end %>
    </div>
    
    <div class="box_left profile">
      <span class="default">名前：</span><span class="unique"><%= link_to "#{@male.name}", @male %></span><br>
      <span class="default">MyPosts:</span> <%= @male.male_posts.count %><span class="unique">  | <%= link_to "#{Relationship.where(male_id: @male.id).count}", following_male_path(id: @male.id) %></span><span class="default">  Followings</span><br>
      <span></span><br>
      <%= link_to 'フォローしてない女医一覧', unfollowing_male_path(id: @male.id) %>
    </div>
    
  </div>
  

  <!-- -likeしてきた女医一覧 -->
  <div>
      <% if @comments.any? %>
        <span class="likealert">likeしてきた女医の連絡先: </span><br>
          <% @comments.each do |comment| %>
            <%= image_tag LadyDoctorPost.find(LadyDoctor.find_by(email: comment).profile_image_id).image.thumb.url %>
            <span class="default">名前：</span><span class="pink"><%= link_to "#{LadyDoctor.find_by(email: comment).name}", lady_doctor_index_path(male_id: @male.id, id: LadyDoctor.find_by(email: comment).id) %><%=  %></span>
            <span class="default">連絡先：</span><span class="pink"><%= comment %>  </span>
            

          <% end %>
        </h3>
      <% end %>
  </div>
  
  
  <div class= "userPostWrapper">
    <% if @lady_doctor_posts.any? %>
      <h3 class="notification"><%= @title %></h3>
      <% @lady_doctor_posts.each do |lady_doctor_post| %>
        <div class="item" >
          <div class="main">
            <div class ="clearfix" >
              <div class="box_left ladyprofile">
                <% if lady_doctor_post.lady_doctor.profile_image_id %>
                  <%= image_tag LadyDoctorPost.find(lady_doctor_post.lady_doctor.profile_image_id).image.thumb.url %>
                <% else %>
                  <%= image_tag 'noimage.gif' %>
                <% end %>
              </div>  


              <div class="box_left profile">
                  <span class="unique"><%= link_to "#{lady_doctor_post.lady_doctor.name}", lady_doctor_posts_show_path(id: lady_doctor_post.id, male_id: @male.id)  %></span> <span class="default">posted my photo.</span><br>
                   <span class="default">Posted at </span><span class="unique"><%= lady_doctor_post.created_at %></span><br>
                   <span class="unique"><%= Relationship.where(lady_doctor_id: lady_doctor_post.lady_doctor.id).count %></span><span class="default">  Followers</span>
              </div>
            </div>
            <!--clearfix-->

            <div class="userContent">
              <% if lady_doctor_post.content %>
                <%= lady_doctor_post.content %>
              <% end %>
            </div>


            <div class="ladyimage">
             <% if lady_doctor_post.image? %>
              <%= image_tag lady_doctor_post.image.url %>
             <% else %>
               <%= image_tag 'noimage.gif' %>
             <% end %>
            </div>
         </div>
         <!--main-->
          
         <div class="_18--"></div>
         <div class="additionpost">
           <span class="default">MyComments: </span><%= MalePostComment.where(lady_doctor_post_id: lady_doctor_post.id, male_id: @male.id).count %> / <span class="default">All </span><%= MalePostComment.where(lady_doctor_post_id: lady_doctor_post.id).count %></span><span class="default">  comments</span><br>
           
           
         </div>
       </div>
       <!--item-->
      <% end %>
  <% end %>
  </div>
  <!-- userPostWrapper -->

<%= link_to 'ログアウト', destroy_male_session_path, method: :delete %>

 </div>
 <!--container -->

app/views/males/lady_doctor_posts_show.html.erb
<div class="container">
  <%= link_to 'このユーザーの詳細を見る', lady_doctor_index_path(id: @lady_doctor.id, male_id: @male.id, lady_doctor_post_id: @lady_doctor_post.id) %>


  <div class="item">
    <div class="main">
      <div class ="clearfix" >
        <div class="box_left ladyprofile">
          <% if @lady_doctor.profile_image_id %>
            <%= image_tag LadyDoctorPost.find(@lady_doctor.profile_image_id).image.thumb.url %>
          <% else %>
            <%= image_tag 'noimage.gif' %>
          <% end %>
        </div>

        <div class="box_left profile">
          <span class="unique"><%= @lady_doctor.name %> </span><span class="default">posted my photo.</span> <br>
          <span class="default">Posted at</span> <span class="unique"><%= @lady_doctor_post.created_at %></span><br>
          <span class="unique"><%= Relationship.where(lady_doctor_id: @lady_doctor.id).count %></span><span class="default">  Followers</span>
        </div>
      </div>
      <!-- clearfix -->

      <div class="userContent">
        <%= @lady_doctor_post.content %>
      </div>

<div class="ladyimage">
      <% if @lady_doctor_post.image? %>
        <%= image_tag @lady_doctor_post.image.url %>
      <% else %>
        <%= image_tag 'noimage.gif' %>
      <% end %>
</div>
    </div>
    
    <!-- main -->
      
    
     
  
  <div class="additionpost">

 <span class="default">MyComments: </span><%= MalePostComment.where(lady_doctor_post_id: @lady_doctor_post.id, male_id: @male.id).count %> / <span class="default">All </span><%= MalePostComment.where(lady_doctor_post_id: @lady_doctor_post.id).count %></span><span class="default">  comments</span><br>

<% @male_post_comments.each do |male_post_comment| %>
  <div class="_18--"></div>
  <span>コメント</span><br>
  <% if @male.profile_image_id %>
    <%= image_tag MalePost.find(@male.profile_image_id).image.thumb.url %>
  <% else %>
    <%= image_tag 'noimage.gif' %>
  <% end %>
  <span class="unique"><%= male_post_comment.male.name %></span>
  <%= male_post_comment.comment %>
  <%= link_to 'Edit', edit_male_post_comment_path(id: male_post_comment.id) %>
  <%= link_to 'Delete', male_post_comment_path(id: male_post_comment.id), method: :delete, data: { confirm: 'Are you sure?' } %>
  <br>
<% end %>
</div>
<!-- additionpost -->
</div>
<!-- item -->

<%= link_to 'New Comment', new_male_post_comment_path(male_id: @male.id, id: @lady_doctor_post.id) %> <br>
<br>
<%= link_to 'Back', males_path %>
</div>
<!-- container -->

app/views/males/show.html.erb
<div class="container">
  <% if @male.age.nil? && @male.profile_image_id.nil? %>
    <span class="notification">自分のプロフィールを編集してね！<br>それができたら、投稿をしてプロフィール画像を設定してね</span>
  <% elsif !@male.age.nil? && @male.profile_image_id.nil? %>
    <span class="notification">投稿をしてプロフィール画像を設定してね</span>
  <% elsif @male.age.nil? && !@male.profile_image_id.nil? %>
    <span class="notification">自分のプロフィールを編集してね！</span>
  <% else %>
    <span class="notification">準備は整った！<br>topページに戻って、気に入った女医をフォローしよう！</span><br>
    <%= link_to 'topに戻る', males_path %>
  <% end %>

  <div class="clearfix userWrapper" >
    <div class="box_left myprofile">
      
      <% if @male_post != nil %>
        <% if @male_post.image? %>
　　       <%= image_tag @male_post.image.thumb.url %>
        <% else %>
　　       <%= image_tag 'noimage.gif' %>
        <% end %>
      <% else %>
        <%= image_tag 'noimage.gif' %>
      <% end %>
    </div>
    <!-- 画像　-->


    <div class="box_left profile">
      <span class="default">名前: </span><span class="unique"><%= @male.name %></span>
      <% if @male.age != nil %>
      <span class="default">   年齢: </span><span class="unique"><%= @male.age %></span><br>
      <% end %>
      <% if @male.work != nil %>
      <span class="default">仕事: </span><span class="unique"><%= @male.work %></span>
      <% end %>
      <% if @male.annual_income != nil %>
      <span class="default">年収: </span><span class="unique"><%= @male.annual_income %></span><br>
      <% end %>
      <br><%= link_to 'Edit My Profile', edit_male_path(id: @male) %><br>
    </div>
    <!-- プロフィール -->

  </div>
  <!--  clearfix userWrapper  -->

  <%= link_to 'New Post', new_male_male_post_path(male_id: @male.id) %> 



  <div class= "userPostWrapper">
    <% @male_posts.each do |male_post| %>
     <div class="item">
      <div class="main">
      <div class ="clearfix" >
        <div class="box_left myprofile">
         <% if @male_post != nil %>
          <% if @male_post.image? %>
　　        <%= image_tag @male_post.image.thumb.url %>
          <% else %>
　　        <%= image_tag 'noimage.gif' %>
          <% end %>
         <% else %>
          <%= image_tag 'noimage.gif' %>
         <% end %>
        </div>
        
        <div class="box_left profile">
          <span class="unique"><%= @male.name %></span>  <span class="default">posted my photo.</span>  <br>
          <span class="default">Posted at </span> <span class="unique"><%= male_post.created_at %></span> 
        </div>
      </div>
      <!--clearfix-->

      <div class="userContent">
        <%= male_post.content %>
      </div>


      <div class="image">
      <% if male_post.image? %>
　　     <%= image_tag male_post.image.url %>
　     <% else %>
　　     <%= image_tag 'noimage.gif' %>
　     <% end %>
      </div>
      </div>
      <!--main-->


      <div class="_18--"></div>
      <div class="additionpost">
      <%= link_to 'Edit', edit_male_male_post_path(male_id: @male.id, id: male_post.id) %>  
      <%= link_to 'Delete', male_male_post_path(male_id: @male.id, id: male_post.id), method: :delete, data: { confirm: 'Are you sure?' } %>
      
        <%= link_to 'これをプロフィール画像にする', male_image_path(male_id: @male.id, id: male_post.id), method: :post %>
      </div>
     </div><!--item -->
    <% end %> 
   
  </div> 
  <!--userPostWrapper -->

  <%= link_to 'Back', males_path %>
</div>